name: HLint
on:
  push:
    paths:
      - '**.hs'
    branches:
      - main
  pull_request:
    paths:
      - '**.hs'
    branches:
      - main
jobs:
  hlint:
    name: HLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.8'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["src/", "app/", "test/"]'
        fail-on: suggestion

